# Generated by Django 4.0.6 on 2024-07-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqf_type', models.CharField(choices=[('80', 'SQF 80'), ('100', 'SQF 100'), ('120', 'SQF 120')], max_length=3)),
                ('specification', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('make', models.CharField(default='default_make_value', max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
