# Generated by Django 4.0.6 on 2024-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('tempering', 'Tempering'), ('washing', 'Washing'), ('traverser', 'Traverser'), ('crossconveyor', 'Cross Conveyor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='make',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='specification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
