# Generated by Django 4.0.6 on 2024-07-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_materialdetail_category_alter_materialdetail_make_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdetail',
            name='category',
        ),
    ]
